
[[dependencies]]
  name = "github.com/DATA-DOG/godog"
  version = ">=0.6.3"

[[dependencies]]
  branch = "topic/hide-selenium-password-from-logged-url"
  name = "github.com/tebeka/selenium"
  source = "github.com/llonchj/selenium"
